"""init

Revision ID: 69c67a564d3e
Revises: 
Create Date: 2024-11-06 07:18:50.085714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c67a564d3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user__id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('file_user', sa.Integer(), nullable=False),
    sa.Column('folderid', sa.Integer(), nullable=False),
    sa.Column('lname', sa.String(length=200), nullable=False),
    sa.Column('fname', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=10000000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=200), nullable=False),
    sa.Column('folder_path', sa.String(length=200), nullable=False),
    sa.Column('folder_user', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=200), nullable=False),
    sa.Column('lname', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loginfailedlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loginlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=200), nullable=False),
    sa.Column('lname', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=250), nullable=False),
    sa.Column('fr', sa.Integer(), nullable=False),
    sa.Column('to', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('fname', sa.String(length=255), nullable=False),
    sa.Column('lname', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signoutlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=200), nullable=False),
    sa.Column('lname', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('fname', sa.String(length=150), nullable=False),
    sa.Column('lname', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=2000), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('advisory', sa.String(length=50), nullable=False),
    sa.Column('img', sa.String(length=2000), nullable=True),
    sa.Column('mblimit', sa.String(length=1000000), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('valid_id', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useractivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website')
    op.drop_table('useractivity')
    op.drop_table('user')
    op.drop_table('signoutlog')
    op.drop_table('position')
    op.drop_table('pm')
    op.drop_table('loginlog')
    op.drop_table('loginfailedlog')
    op.drop_table('folders')
    op.drop_table('files')
    op.drop_table('chat')
    op.drop_table('announcement')
    op.drop_table('advisory')
    op.drop_table('admin')
    # ### end Alembic commands ###
